name: html-minifier
on: workflow_dispatch
jobs:
  minify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install html-minifier -g
      - run: html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true src/index.html > docs/index.html
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: docs